package view;
import Contraints.Constant;
import java.time.LocalDate;
import Model.Flights;
import Controller.ticketsearchcontroller;
import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


public class Ticket2 extends javax.swing.JFrame {

    /**
     * Creates new form Ticket2
     */
    public Ticket2() {
        initComponents();
 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        rTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jpanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        departure = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jcall1 = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        location1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        returns = new javax.swing.JTextField();
        donb = new javax.swing.JButton();
        jcall2 = new com.toedter.calendar.JDateChooser();
        jButton9 = new javax.swing.JButton();
        buttonOne = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 800));

        kGradientPanel1.setkEndColor(new java.awt.Color(51, 0, 102));
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 102, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        gTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline Name", "Location 1", "Location 2", "Departure Time", "Arrival Time", "Departure Date", "Duration", "Business Price", "Economy Price", "Cabin Capacity", "Checkin Capacity", "Refundable"
            }
        ));
        gTable.setFocusable(false);
        gTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gTable);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DETAILS");

        rTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline Name", "Location 2", "Location 1", "Departure Time", "Arrival Time", "Departure Date", "Duration", "Business Price", "Economy Price", "Cabin Capacity", "Checkin Capacity", "Refundable"
            }
        ));
        rTable.setFocusable(false);
        rTable.setRequestFocusEnabled(false);
        jScrollPane3.setViewportView(rTable);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("GOING");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("RETURNING");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton2.setText("Business");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setText("Economy");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jButton8.setText("Book");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(541, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(536, 536, 536))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jButton8))
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addGap(53, 53, 53))
        );

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setText("View Refundable flights only");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setText("Sort highest to lowest");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton3.setText("Sort lowest to highest");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(298, 71));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8-home-page-64.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8-available-updates-64.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8-male-user-64.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8-logout-64.png"))); // NOI18N
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addGap(0, 76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/High Fid. Prototype (1).png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel7.setText("Location");

        location.setBackground(new java.awt.Color(204, 204, 255));
        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel9.setText("Date of departure");

        departure.setBackground(new java.awt.Color(204, 204, 255));
        departure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureActionPerformed(evt);
            }
        });

        jButton10.setText("Done");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jcall1.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jpanel4Layout = new javax.swing.GroupLayout(jpanel4);
        jpanel4.setLayout(jpanel4Layout);
        jpanel4Layout.setHorizontalGroup(
            jpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
            .addGroup(jpanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanel4Layout.createSequentialGroup()
                        .addGroup(jpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jpanel4Layout.createSequentialGroup()
                                .addComponent(departure, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcall1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jpanel4Layout.setVerticalGroup(
            jpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel4Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jpanel4Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(departure, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jcall1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel4Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jButton10)))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/High Fid. Prototype.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel8.setText("Location");

        location1.setBackground(new java.awt.Color(204, 204, 255));
        location1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                location1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel10.setText("Date of return");

        returns.setBackground(new java.awt.Color(204, 204, 255));

        donb.setText("Done");
        donb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donbActionPerformed(evt);
            }
        });

        jcall2.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(location1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(returns, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcall2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(donb, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(location1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jcall2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(returns, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(donb)))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setText("Search Flights");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        buttonGroup3.add(buttonOne);
        buttonOne.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        buttonOne.setForeground(new java.awt.Color(255, 255, 255));
        buttonOne.setText("One Way");
        buttonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOneActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Two Way");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Mountain Flight");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(jButton9))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(buttonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168)
                        .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(jRadioButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jpanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(192, 192, 192))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOne)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //Sorting
        TableRowSorter<TableModel> sorter2 = new TableRowSorter<TableModel>(gTable.getModel());
        gTable.setRowSorter(sorter2);
        ArrayList<RowSorter.SortKey> sortKeys2 = new ArrayList<RowSorter.SortKey>();
 
        int columnIndexToSort2 = 8;
        sortKeys2.add(new RowSorter.SortKey(columnIndexToSort2, SortOrder.ASCENDING));
 
        sorter2.setSortKeys(sortKeys2);
        sorter2.sort();
        
        TableRowSorter<TableModel> sorter3 = new TableRowSorter<TableModel>(rTable.getModel());
        rTable.setRowSorter(sorter3);
        ArrayList<RowSorter.SortKey> sortKeys3 = new ArrayList<RowSorter.SortKey>();
 
        int columnIndexToSort3 = 8;
        sortKeys3.add(new RowSorter.SortKey(columnIndexToSort3, SortOrder.ASCENDING));
 
        sorter3.setSortKeys(sortKeys3);
        sorter3.sort();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Refundable
        DefaultTableModel tb1Model3= (DefaultTableModel)gTable.getModel();
        TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel>(tb1Model3);
        gTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("Yes"));
        
        DefaultTableModel tb1Model4= (DefaultTableModel)rTable.getModel();
        TableRowSorter<DefaultTableModel> tr2= new TableRowSorter<DefaultTableModel>(tb1Model4);
        rTable.setRowSorter(tr2);
        tr2.setRowFilter(RowFilter.regexFilter("Yes"));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       //dashboard
        this.setVisible(false);
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dbf().setVisible(true);
            }
        });
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //refresh
        setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //Logout
       int value=JOptionPane.showConfirmDialog(null, "Are you sure you want to Logout?", "Logout", JOptionPane.YES_NO_OPTION);
        if(value==0){
        this.dispose();
        Constant.loggedInUser = null;
        new LoginScreen().setVisible(true);   }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        //if block
        if (buttonOne.isSelected()){
        int column5= 8;
        int row5= gTable.getSelectedRow();
        String value5= gTable.getModel().getValueAt(row5,column5).toString();
        System.out.println(value5);}
        // else if block
        else if(jRadioButton4.isSelected()){
            int column6 =8;
            int column7=8;
        
            int row6=gTable.getSelectedRow();
            int row7=rTable.getSelectedRow();
            String value6=gTable.getModel().getValueAt(row6,column6).toString();
            String value7=rTable.getModel().getValueAt(row7,column7).toString();
            int value8= Integer.parseInt (value6)+Integer.parseInt(value7);
            System.out.println(value8);
            //print
        }else if(jRadioButton3.isSelected()){
            int column8= 8;
        int row8= gTable.getSelectedRow();
        String value9= gTable.getModel().getValueAt(row8,column8).toString();
        System.out.println(value9);
        
        }

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        //Sorting
        if (buttonOne.isSelected()){
        int column= 7;
        int row= gTable.getSelectedRow();
        String value= gTable.getModel().getValueAt(row,column).toString();
        System.out.println(value);}
        
        else if(jRadioButton4.isSelected()){
            int column1 =7;
            int column2=7;
        
            int row1=gTable.getSelectedRow();
            int row2=rTable.getSelectedRow();
            String value1=gTable.getModel().getValueAt(row1,column1).toString();
            String value2=rTable.getModel().getValueAt(row2,column2).toString();
            int value3= Integer.parseInt (value1)+Integer.parseInt(value2);
            System.out.println(value3);
            
        }else if(jRadioButton3.isSelected() ){
            int column3= 7;
        int row3= gTable.getSelectedRow();
        String value4= gTable.getModel().getValueAt(row3,column3).toString();
        System.out.println(value4);
        
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    
         //Flight classes   
     String dep_loc=location.getText();
     String arri_loc=location1.getText();
     String dep_date=departure.getText();
     String ret_date= returns.getText();
     
     if(location.getText().isEmpty()|| location1.getText().isEmpty()|| departure.getText().isEmpty()||buttonGroup3.getSelection()==null){
         JOptionPane.showMessageDialog(this,"All fields are required");

     }
     if(buttonOne.isSelected()){
         if(location.getText().isEmpty()|| location1.getText().isEmpty()|| departure.getText().isEmpty()){
                         JOptionPane.showMessageDialog(this,"All fields are required");

         }
         else{
           Flights f1= new Flights(arri_loc,dep_loc,dep_date);
           
           ticketsearchcontroller t1= new ticketsearchcontroller();
           
           try {
               
               
//               
               
               ResultSet flightResult= t1.retrieveflights(f1);
               
               
               if(flightResult.next()){
               flightResult= t1.retrieveflights(f1);
               
               DefaultTableModel tb1Model= (DefaultTableModel)gTable.getModel();
               while(tb1Model.getRowCount() > 0){ tb1Model.removeRow(0);}
               while (flightResult.next()){
                   
                   String resultAirlineName=flightResult.getString("airline_name");
                   String resultDeparture=flightResult.getString("departure");
                   String resultDestination= flightResult.getString("destination");
                   String resultDTime= flightResult.getString("departure_time");
                   String resultATime= flightResult.getString("arrival_time");
                   String resultDDate= String.valueOf(flightResult.getDate("departure_date"));
                   String resultDuration= flightResult.getString("duration");
                   String resultBPrice= String.valueOf(flightResult.getString("business_price"));
                   String resultEPrice= String.valueOf(flightResult.getString("economy_price"));
                   String resultCabin= flightResult.getString("cabin_capacity");
                   String resultCheckin= flightResult.getString("checkin_capacity");
                   String resultRefundable= flightResult.getString("refundable");
                  
                   
                   String tbData[] = {resultAirlineName,resultDeparture,resultDestination,resultDTime,resultATime,resultDDate,resultDuration,
                       resultBPrice,resultEPrice,resultCabin,resultCheckin,resultRefundable
                    };
                   
                   tb1Model.addRow(tbData);
                   
               }
    
           }
               else{
                   JOptionPane.showMessageDialog(this,"No such flights found");
               }
           } catch (SQLException ex) {
               Logger.getLogger(Ticket2.class.getName()).log(Level.SEVERE, null, ex);
           }
          
           }
        
        
     }
     
     else if(jRadioButton4.isSelected()){
     if(location.getText().isEmpty()|| location1.getText().isEmpty()|| departure.getText().isEmpty()||  returns.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"All fields are required");
        }
        else{
           Flights f1= new Flights(arri_loc,dep_loc,dep_date);
           Flights f2= new Flights(dep_loc,arri_loc,ret_date);
           ticketsearchcontroller t1= new ticketsearchcontroller();
           
           try {
               
               
              
               
               ResultSet flightResult= t1.retrieveflights(f1);
               ResultSet flightResult2 = t1.retrieveflights(f2);
               
               if(flightResult.next() && flightResult2.next()){
               flightResult= t1.retrieveflights(f1);
               
               DefaultTableModel tb1Model= (DefaultTableModel)gTable.getModel();
               while(tb1Model.getRowCount() > 0){ tb1Model.removeRow(0);}
               while (flightResult.next()){
                   
                   String resultAirlineName=flightResult.getString("airline_name");
                   String resultDeparture=flightResult.getString("departure");
                   String resultDestination= flightResult.getString("destination");
                   String resultDTime= flightResult.getString("departure_time");
                   String resultATime= flightResult.getString("arrival_time");
                   String resultDDate= String.valueOf(flightResult.getDate("departure_date"));
                   String resultDuration= flightResult.getString("duration");
                   String resultBPrice= String.valueOf(flightResult.getString("business_price"));
                   String resultEPrice= String.valueOf(flightResult.getString("economy_price"));
                   String resultCabin= flightResult.getString("cabin_capacity");
                   String resultCheckin= flightResult.getString("checkin_capacity");
                   String resultRefundable= flightResult.getString("refundable");
                  
                   
                   String tbData[] = {resultAirlineName,resultDeparture,resultDestination,resultDTime,resultATime,resultDDate,resultDuration,
                       resultBPrice,resultEPrice,resultCabin,resultCheckin,resultRefundable
                    };
                   
                   tb1Model.addRow(tbData);
                   
               }
                   flightResult2 = t1.retrieveflights(f2);
                   DefaultTableModel tb1Model2= (DefaultTableModel)rTable.getModel();
                   while(tb1Model2.getRowCount() > 0){ tb1Model2.removeRow(0);}
                   while (flightResult2.next()){
                   String resultAirlineName=flightResult2.getString("airline_name");
                   String resultDeparture=flightResult2.getString("departure");
                   String resultDestination= flightResult2.getString("destination");
                   String resultDTime= flightResult2.getString("departure_time");
                   String resultATime= flightResult2.getString("arrival_time");
                   String resultDDate= String.valueOf(flightResult2.getDate("departure_date"));
                   String resultDuration= flightResult2.getString("duration");
                   String resultBPrice= String.valueOf(flightResult2.getString("business_price"));
                   String resultEPrice= String.valueOf(flightResult2.getString("economy_price"));
                   String resultCabin= flightResult2.getString("cabin_capacity");
                   String resultCheckin= flightResult2.getString("checkin_capacity");
                   String resultRefundable= String.valueOf(flightResult2.getString("refundable"));
                   
                   
                   String tbData2[] = {resultAirlineName,resultDeparture,resultDestination,resultDTime,resultATime,resultDDate,resultDuration,
                       resultBPrice,resultEPrice,resultCabin,resultCheckin,resultRefundable
                   };
                   
                   tb1Model2.addRow(tbData2);
               }
                   
                   
                   
                   
                   
               
           
           }
               else{
                   JOptionPane.showMessageDialog(this,"No such flights found");
               }
           } catch (SQLException ex) {
               Logger.getLogger(Ticket2.class.getName()).log(Level.SEVERE, null, ex);
           }
           }
          
           
       } 
               
    
    else if(jRadioButton3.isSelected()){
         if(location.getText().isEmpty()|| location1.getText().isEmpty()|| departure.getText().isEmpty()){
                         JOptionPane.showMessageDialog(this,"All fields are required");
        }
        else{
           Flights f1= new Flights(arri_loc,dep_loc,dep_date);
           ticketsearchcontroller t1= new ticketsearchcontroller();
           
           try {
               
               
         
               
               ResultSet flightResult= t1.retrieveflights(f1);

               
               if(flightResult.next()){
               flightResult= t1.retrieveflights(f1);
               
               DefaultTableModel tb1Model3= (DefaultTableModel)gTable.getModel();
               while(tb1Model3.getRowCount() > 0){ tb1Model3.removeRow(0);}
               while (flightResult.next()){
                   
                   String resultAirlineName=flightResult.getString("airline_name");
                   String resultDeparture=flightResult.getString("departure");
                   String resultDestination= flightResult.getString("destination");
                   String resultDTime= flightResult.getString("departure_time");
                   String resultATime= flightResult.getString("arrival_time");
                   String resultDDate= String.valueOf(flightResult.getDate("departure_date"));
                   String resultDuration= flightResult.getString("duration");
                   String resultBPrice= String.valueOf(flightResult.getString("business_price"));
                   String resultEPrice= String.valueOf(flightResult.getString("economy_price"));
                   String resultCabin= flightResult.getString("cabin_capacity");
                   String resultCheckin= flightResult.getString("checkin_capacity");
                   String resultRefundable= flightResult.getString("refundable");
                  
                





//                   String resultDestination= flightResult2.getString("destination");
//                   String resultDTime= flightResult2.getString("departure_time");
//                   String resultATime= flightResult2.getString("arrival_time");
//                   String resultDDate= String.valueOf(flightResult2.getDate("departure_date"));
//                   String resultDuration= flightResult2.getString("duration");
//                   String resultBPrice= String.valueOf(flightResult2.getString("business_price"));
//                   String resultEPrice= String.valueOf(flightResult2.getString("economy_price"));
//                   String resultCabin= flightResult2.getString("cabin_capacity");
//                   String resultCheckin= flightResult2.getString("checkin_capacity");
//                   String resultRefundable= String.valueOf(flightResult2.getString("refundable"));
                   
                   
                   String tbData[] = {resultAirlineName,resultDeparture,resultDestination,resultDTime,resultATime,resultDDate,resultDuration,
                       resultBPrice,resultEPrice,resultCabin,resultCheckin,resultRefundable
                   };
                   
                   tb1Model3.addRow(tbData);
               }
                   
//                   
//                   
//                   
//                   
//               
           
           }
               else{
                   JOptionPane.showMessageDialog(this,"No such flights found");
               }
           } catch (SQLException ex) {
               Logger.getLogger(Ticket2.class.getName()).log(Level.SEVERE, null, ex);
           }
      }
        
         
     }
     
//     

              
    }//GEN-LAST:event_jButton9ActionPerformed

    private void buttonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOneActionPerformed
        // TODO add your handling code here: 
        returns.setEnabled(false);
    
    
    }//GEN-LAST:event_buttonOneActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        returns.setEnabled(true);
       
        
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        returns.setEnabled(false);
        
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void departureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureActionPerformed
        // TODO add your handling code here:
//        departure.setText();
        
    
        
        
        
        
    }//GEN-LAST:event_departureActionPerformed

    private void jcall1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcall1MouseClicked
        // TODO add your handling code here:
        
//        departure.show();
    }//GEN-LAST:event_jcall1MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
//        Date date = jcall1.getDate();
        String selectdate=((JTextField)jcall1.getDateEditor().getUiComponent()).getText();
       
//          String strDate = DateFormat.getDateInstance().format(date);
        departure.setText(selectdate);
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void donbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donbActionPerformed
        // TODO add your handling code here:
        String selectdat=((JTextField)jcall2.getDateEditor().getUiComponent()).getText();
        returns.setText(selectdat);
    }//GEN-LAST:event_donbActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(gTable.getModel());
        gTable.setRowSorter(sorter);
        ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>();
 
        int columnIndexToSort = 8;
        sortKeys.add(new RowSorter.SortKey(columnIndexToSort, SortOrder.DESCENDING));
 
        sorter.setSortKeys(sortKeys);
        sorter.sort();
        
        TableRowSorter<TableModel> sorter1 = new TableRowSorter<TableModel>(rTable.getModel());
        rTable.setRowSorter(sorter1);
        ArrayList<RowSorter.SortKey> sortKeys1 = new ArrayList<RowSorter.SortKey>();
 
        int columnIndexToSort1 = 8;
        sortKeys1.add(new RowSorter.SortKey(columnIndexToSort1, SortOrder.DESCENDING));
 
        sorter1.setSortKeys(sortKeys1);
        sorter1.sort();
        
     
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         BookingConf booking= new BookingConf();
         
        if(buttonOne.isSelected() || jRadioButton3.isSelected()){
                  
        int index=gTable.getSelectedRow();
        TableModel model=gTable.getModel();
        
        
        String fromd =model.getValueAt(index,1).toString();
        String tod =model.getValueAt(index,2).toString();
        String departd =model.getValueAt(index,5).toString();
        
        
        String durationd =model.getValueAt(index,6).toString();
        String cabinLimitd =model.getValueAt(index,9).toString();
        String checkinLimitd =model.getValueAt(index,10).toString();
        String aName= model.getValueAt(index,0).toString();
        
        booking.setVisible(true);
        booking.pack();
        booking.setLocationRelativeTo(null);
        booking.dFrom.setText(fromd);
        booking.dTo.setText(tod);
        booking.dDar.setText(departd);
        booking.dAName.setText(aName);
        booking.dDura.setText(durationd);
        booking.dCabLim.setText(cabinLimitd);
        booking.dChecklim.setText(checkinLimitd);
        if(jRadioButton1.isSelected()){
            String ePrice1=model.getValueAt(index,8).toString();
            booking.dPrice.setText(ePrice1);
            booking.pTextField.setText(ePrice1);
        }
        else if(jRadioButton2.isSelected()){
            String ePrice1=model.getValueAt(index,7).toString();
            booking.dPrice.setText(ePrice1);
            booking.pTextField.setText(ePrice1);
        }
        
        }
        
        if(jRadioButton4.isSelected()){
        int index1=rTable.getSelectedRow();
        TableModel mdl=rTable.getModel();
        
        int index=gTable.getSelectedRow();
        TableModel model=gTable.getModel();
        
        
        String fromd =model.getValueAt(index,1).toString();
        String tod =model.getValueAt(index,2).toString();
        String departd =model.getValueAt(index,5).toString();
        
        
        String durationd =model.getValueAt(index,6).toString();
        String cabinLimitd =model.getValueAt(index,9).toString();
        String checkinLimitd =model.getValueAt(index,10).toString();
        String aName= model.getValueAt(index,0).toString();
        
        booking.setVisible(true);
        booking.pack();
        booking.setLocationRelativeTo(null);
        booking.dFrom.setText(fromd);
        booking.dTo.setText(tod);
        booking.dDar.setText(departd);
        
        booking.dDura.setText(durationd);
        booking.dCabLim.setText(cabinLimitd);
        booking.dChecklim.setText(checkinLimitd);
        booking.dAName.setText(aName);
        
        
        String durationa=mdl.getValueAt(index1,6).toString();
        String toa=mdl.getValueAt(index1,2).toString();
        String departura=mdl.getValueAt(index1,5).toString();
        String froma=mdl.getValueAt(index1,1).toString();
        String cabinlimita=mdl.getValueAt(index1,9).toString();
        String checkinlimita=mdl.getValueAt(index1,10).toString();
        String aName2= mdl.getValueAt(index1,0).toString();
        
        
        
        
      
        booking.aDura.setText(durationa);
        booking.aTo.setText(toa);
        booking.aAr.setText(departura);
        booking.aFrom.setText(froma);
        booking.aCablim.setText(cabinlimita);
        booking.aChecklim.setText(checkinlimita);
        booking.aName2.setText(aName2);
        
        if(jRadioButton1.isSelected()){
            String ePrice1=model.getValueAt(index,8).toString();
            String ePrice2=mdl.getValueAt(index1,8).toString();
            booking.dPrice.setText(ePrice1);
            booking.aPrice.setText(ePrice2);
            int intEPrice1= parseInt(ePrice1);
            int intEPrice2=parseInt(ePrice2);
            int totalPrice= intEPrice1+intEPrice2;
            String stotalPrice= String.valueOf(totalPrice);
            booking.pTextField.setText(stotalPrice);
        }
        else if(jRadioButton2.isSelected()){
            String ePrice1=model.getValueAt(index,7).toString();
            String ePrice2=mdl.getValueAt(index1,7).toString();
            booking.dPrice.setText(ePrice1);
            booking.aPrice.setText(ePrice2);
            int intEPrice1= parseInt(ePrice1);
            int intEPrice2=parseInt(ePrice2);
            int totalPrice= intEPrice1+intEPrice2;
            String stotalPrice= String.valueOf(totalPrice);
            booking.pTextField.setText(stotalPrice);
        }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ChangeProfile().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton buttonOne;
    private javax.swing.JTextField departure;
    private javax.swing.JButton donb;
    private javax.swing.JTable gTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jcall1;
    private com.toedter.calendar.JDateChooser jcall2;
    private javax.swing.JPanel jpanel4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField location;
    private javax.swing.JTextField location1;
    private javax.swing.JTable rTable;
    private javax.swing.JTextField returns;
    // End of variables declaration//GEN-END:variables
}
